/**
 * Quick smoke test for src/integrations/github.ts
 * Run with:  npx ts-node scripts/test-github.ts
 *
 * With GITHUB_TOKEN unset → uses mock mode (safe, no real API calls).
 * With GITHUB_TOKEN set   → hits the real GitHub API against TEST_REPO.
 */

import "dotenv/config";
import {
  getFileTree,
  getFileContent,
  createBranch,
  applyDiff,
  openPR,
  triggerWorkflow,
  getWorkflowRuns,
} from "../src/integrations/github";

const REPO = process.env.TEST_REPO ?? "nexguard-org/demo-app";
const MOCK = !process.env.GITHUB_TOKEN;

console.log(`\n=== github.ts smoke test (${MOCK ? "MOCK" : "LIVE"}) ===\n`);

async function run() {
  // 1. getFileTree
  console.log("1. getFileTree...");
  const tree = await getFileTree(REPO);
  console.log(`   ✓ ${tree.length} files:`, tree.slice(0, 3).join(", "));

  // 2. getFileContent
  console.log("2. getFileContent...");
  const content = await getFileContent(REPO, tree[0]);
  console.log(`   ✓ ${tree[0]} (${content.length} chars)`);

  // 3. createBranch
  const branch = `nexguard/test-${Date.now()}`;
  console.log(`3. createBranch → ${branch}...`);
  await createBranch(REPO, branch);
  console.log("   ✓ branch created");

  // 4. applyDiff
  console.log("4. applyDiff...");
  const fakeDiff = `diff --git a/test-file.ts b/test-file.ts
--- a/test-file.ts
+++ b/test-file.ts
@@ -0,0 +1,3 @@
+// auto-generated by NexGuard
+export const hello = "world";
`;
  await applyDiff(REPO, branch, fakeDiff, "chore: nexguard smoke test");
  console.log("   ✓ diff applied");

  // 5. openPR
  console.log("5. openPR...");
  const prUrl = await openPR(REPO, branch, "[NexGuard] Smoke test PR", "Automated smoke test.");
  console.log(`   ✓ PR: ${prUrl}`);

  // 6. triggerWorkflow
  console.log("6. triggerWorkflow...");
  await triggerWorkflow(REPO, "ci.yml");
  console.log("   ✓ workflow dispatched");

  // 7. getWorkflowRuns
  console.log("7. getWorkflowRuns...");
  const runs = await getWorkflowRuns(REPO, "ci.yml");
  console.log(`   ✓ ${runs.length} run(s), latest status: ${runs[0]?.status}`);

  console.log("\n✅ All checks passed\n");
}

run().catch((err) => {
  console.error("\n❌ Test failed:", err.message);
  process.exit(1);
});
